// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValsquadTaskSystemManagementCars.Model;

#nullable disable

namespace ValsquadTaskSystemManagementCars.Migrations
{
    [DbContext(typeof(ManagementCarsDBContext))]
    partial class ManagementCarsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ValsquadTaskSystemManagementCars.Model.Car", b =>
                {
                    b.Property<string>("PlateNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlateNumber");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("ValsquadTaskSystemManagementCars.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ValsquadTaskSystemManagementCars.Model.EmployeeCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CarsPlateNumber")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CountAccess")
                        .HasColumnType("int");

                    b.Property<int>("CountAccessSameMinute")
                        .HasColumnType("int");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateTimeNow")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarsPlateNumber");

                    b.HasIndex("EmployeesId");

                    b.ToTable("EmployeeCard");
                });

            modelBuilder.Entity("ValsquadTaskSystemManagementCars.Model.EmployeeCard", b =>
                {
                    b.HasOne("ValsquadTaskSystemManagementCars.Model.Car", "Cars")
                        .WithMany()
                        .HasForeignKey("CarsPlateNumber");

                    b.HasOne("ValsquadTaskSystemManagementCars.Model.Employee", "Employees")
                        .WithMany("EmployeeCards")
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cars");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ValsquadTaskSystemManagementCars.Model.Employee", b =>
                {
                    b.Navigation("EmployeeCards");
                });
#pragma warning restore 612, 618
        }
    }
}
